### ISSUE TITLE
Adjust displaying of bars

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#32]
Data visualisation in Pareto chart is currently out of scope/ overlaps axis and not centred, for reference see pictures 

To do:  
- fix overlapping of bars with axis. 
- fix issue with bars not aligned with x-axis categories
- fix issue with bars layout in comparision with y-axis and percentage-scale

Acceptance Criteria: 
When displaying multiple bars the size of the bar charts should not exceed and overlap with the axes. 
The category bar should be displayed above the corresponding category tag. 
The bars should be aligned central to the three axes. 

![Image](https://user-images.githubusercontent.com/81046735/193269925-b97a37c2-dc81-467f-b988-142a6d1c696b.png)

![Image](https://user-images.githubusercontent.com/81046735/193597496-ee9a73f1-99ae-4611-b012-04c6892bd9e1.png)

**Comment by gusmalikah** [comment]
Now the overlap of the bars is fixed and they are displayed within the axis and if more bars are added then the width is adjusted accordingly.

![Image](https://user-images.githubusercontent.com/71040758/193911462-b30675f8-db41-43f1-9f96-177837f30428.png)

**Comment by b4rdha** [comment]
The multiple categories (see picture one) are still not adjusted, won't fix for sprint 2, so not included on the MVP. Will be added to backlog and worked on the next sprint.
